### ISSUE TITLE
ECONNREFUSED error when launching browser with running fresh install on windows

### ISSUE THREAD

**Issue by MichaelJohnCoan** [eclipse/sirius-components#89]
## 🐛 Bug Report
* [X] Can you reproduce the problem all the time?
* [X] Are you running the latest version?
* [X] Did you check the documentation?
* [X] Are you reporting this issue to the correct repository?
* [X] Did you perform a search to check if the issue does not exist already?

## Current behavior
After performing yarn start, the browser tab starts and displays:
![image](https://user-images.githubusercontent.com/7872418/42092903-905ea3da-7b78-11e8-9436-0fdb89b7241f.png)

Watching in process explorer, some node processes start, but one seems to die after starting--leaving the others running.

Command line displays:
Proxy error: Could not proxy request /api/dashboard from localhost:3000 to http://localhost:8080/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
[HPM] Error occurred while trying to proxy request /api/dashboard from localhost:3000 to http://localhost:8080/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_
common_system_errors)

## Expected behavior
Dashboard should display correctly

## Steps to reproduce
yarn start from command line

## Environment
Sirius Components [latest]
Eclipse Photon [latest]
Sirius 6.0

Browser in which the issue has been reproduced:
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
 
For Tooling issues:
* Yarn version: 1.3.2
* Node version: v9.5.0
* Platform: Windows 10 Enterprise version 1607

Others:

**Comment by MichaelJohnCoan** [comment]
Looking at my Sirius install, the Sirius Server will not install.  I get this:
![image](https://user-images.githubusercontent.com/7872418/42098065-ce528f1c-7b87-11e8-91ee-82eb480f2896.png)

**Comment by MichaelJohnCoan** [comment]
Attempting the other (Experimental) Sirius installs [that I assume are also needed], I get similar results.  Any reason what I need to change?
![image](https://user-images.githubusercontent.com/7872418/42098243-51716d96-7b88-11e8-8b2e-b8483c377506.png)

**Comment by MichaelJohnCoan** [comment]
I was finally able to isolate the dependencies needed for the Sirius Server et al by installing:
org.eclipse.jetty.servlets [9.0.0,10.0.0) dependencies.  That allowed the Server and Workflow experimental packages to install.  However, I get the same error in the browser (ECONNREFUSED).

Looking at the process explorer, there are 3 nodejs processes created and now they all continue to run.  The last created nodejs process gets a good amount of CPU run time as the browser tab spins up before the error in the workflow diagram element shows the error.

**Comment by MichaelJohnCoan** [comment]
The HTTP traffic looks like:
![image](https://user-images.githubusercontent.com/7872418/42240600-ccff8056-7ed5-11e8-9019-8282de788afb.png)

**Comment by MichaelJohnCoan** [comment]
The HTTP traffic looks like:
![image](https://user-images.githubusercontent.com/7872418/42240646-f888c9d0-7ed5-11e8-9934-eaea5405999a.png)

**Comment by sbegaudeau** [comment]
Hi,

Sorry for the delay but I was away for a couple of days and since this code is quite new and I'm the one who wrote most of it, the team was waiting for me to return to answer this issue.

From what I understand from your very detailed messages, we may want to bundle the necessary Jetty bundle in our server feature, to simplify the installation. In any case, for the next release we will have [a dedicated product](https://git.eclipse.org/r/#/c/124325/) to launch the server so it will be easier to get started.

Now, your issue seems to be that the front-end cannot find the backend. There are two possibilities, either the server is not running or it does not run on the expected port (or something is very broken). In your Eclipse instance, you can open the Console view and start a new Host OSGi Console.

![](https://i.imgur.com/9y0soEq.png)

Once your OSGi console is running, you will be able to see the state of your Eclipse instance. In this case, you should first see if the server is running with ```ss org.eclipse.sirius.server```. You should see something like this:

![](https://i.imgur.com/tLBaJct.png)

If the components org.eclipse.sirius.server and org.eclipse.sirius.server.backend are not active, you may be missing the org.eclipse.sirius.server.ui.autostart component which, as its name implies, starts the server automatically. In any case, you can start the server manually by using ```start <ID>``` with ID being the identifier of the component displayed in the console. In my case, it would be ```start 524``` (see the previous screenshot for the ID of the server component in my Eclipse instance).

If the server is up and running like in my screenshot, then the issue must be coming from the fact that it did not start on the port 8080. While running the Sirius Component code in a development environment, it expect the server to be available on localhost:8080 (just like in the first error message that you have reported). By default, the Sirius server will tell Jetty to use a random port.

In order to tell Sirius to start the server on a specific port, an environment variable can be configured. You can thus launch your Eclipse instance with the following parameter to ensure that the Sirius server will be started on the port 8080 ```-DSIRIUS_SERVER_PORT=8080```.

In order to make sure that all of our environment variable look the same, this environment variable will be modified in the next release to ```-Dorg.eclipse.sirius.server.http.port=8080```.

**Comment by MichaelJohnCoan** [comment]
Hi,

I must apologize for my delay getting back to you, but I was on a brief holiday.

Here is what I am trying with your assistance:

I start eclipse with the environment variable:
![image](https://user-images.githubusercontent.com/7872418/42453849-f3291992-835b-11e8-9970-6eab99a21c3a.png)

I run the example:
![image](https://user-images.githubusercontent.com/7872418/42453881-0dc6f0da-835c-11e8-96a2-b78f5e8b3028.png)

And check the OSGi console:
![image](https://user-images.githubusercontent.com/7872418/42453914-2422c5de-835c-11e8-9f1e-926abac13a04.png)

But I get the same error:
![image](https://user-images.githubusercontent.com/7872418/42453945-3e174014-835c-11e8-97d9-96fa0f4f786d.png)

I am very new to Eclipse and Sirius.

**Comment by sbegaudeau** [comment]
Hi,

Could you add the environment variable in your eclipse.ini and could you make sure to have ```-console``` and ```-consoleLog``` too. You should have something like that in the end in your eclipse.ini

```
-startup
plugins/org.eclipse.equinox.launcher_xxxxxxxx.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.xxxxxxxxxxxx
-console
-consoleLog
-vmargs
-Dorg.eclipse.sirius.server.http.port=8080
-DSIRIUS_SERVER_PORT=8080
```

Then start your Eclipse using a terminal and check what appears in the terminal. You should see something like this:

```
2018-07-10 08:42:22.000:INFO:oejsh.ContextHandler:Start Level: Equinox Container: f6054c6d-3728-4364-982b-77f2562a7625: Started o.e.j.s.ServletContextHandler@732d4054{/,null,AVAILABLE}
2018-07-10 08:42:22.046:INFO:oejs.AbstractConnector:Start Level: Equinox Container: f6054c6d-3728-4364-982b-77f2562a7625: Started ServerConnector@7fe943de{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-07-10 08:42:22.046:INFO:oejs.Server:Start Level: Equinox Container: f6054c6d-3728-4364-982b-77f2562a7625: Started @3266ms
```

The part ```{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}``` indicates on which port, here 8080, the Jetty server has been started.

**Comment by MichaelJohnCoan** [comment]
Hi,

Once I modified my eclipse.ini file, it seems to work!  See below:
![image](https://user-images.githubusercontent.com/7872418/42534125-dfc42460-8459-11e8-9668-e632debefdb9.png)

Thanks very much for your assistance!
